### ISSUE TITLE
Quickstart Guide contains link leading to page not found

### ISSUE THREAD

**Issue by spprichard** [SeldonIO/tempo#177]
When looking over the Quickstart [guide,](https://github.com/SeldonIO/tempo/blob/master/docs/overview/quickstart.md#quickstart), in the [Next Step](https://github.com/SeldonIO/tempo/blob/master/docs/overview/quickstart.md#next-step) section,  the `introductory example` link leads to a page not found 

![image](https://user-images.githubusercontent.com/10872240/127697832-81fb9e5e-2fd0-4d86-ac33-22872bf8d170.png)

**Comment by cliveseldon** [comment]
This is because the docs are meant to be read from readthedocs website, so its pointing at https://tempo.readthedocs.io/en/latest/examples/custom-model/README.html

Not sure we can do anything for the github source files to make them also work as the files are markdown but sphinx turns them into html. Will close  - can reopen is anyone has any ideas.
